To close all pull requests to a single repository, create the following file at .github/mistaken-pull-closer.yml:

# The JSONPath filter expression used to identify which PRs to close.
# The data filtered is the pull request data along with other metadata passed in
# by probot.
# See http://linkremoved/
# `true` will close all PRs.
filters:
  - true

# The message to post to the closed PR.
commentBody: |
  Hi! Thanks for your contribution!
  
  We have to close all the pull requests due to security reasons.
  
  @dkurt, please review
