name: Build for RISC-V

on: [workflow_dispatch, pull_request]
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Clone
      run: |
        git clone https://github.com/opencv/opencv --depth 1
        git clone --recurse-submodules -j$(nproc --all) https://github.com/openvinotoolkit/openvino --depth 1 -b releases/2022/2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y crossbuild-essential-riscv64

        sudo dpkg --add-architecture riscv64
        sudo sed -i -E 's|^deb ([^ ]+) (.*)$|deb [arch=amd64] \1 \2\ndeb [arch=riscv64] http://ports.ubuntu.com/ubuntu-ports/ \2|' /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libusb-1.0-0-dev:riscv64 \
          libpython3-dev:riscv64 \
          cython3

        python3 -m pip install numpy==1.21.5
        python3 -c "import numpy; print(numpy.__version__); print(numpy.__file__)"

    - name: Build OpenCV
      run: |        
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=$(realpath opencv/platforms/linux/riscv64-gnu.toolchain.cmake) \
          -DCMAKE_INSTALL_PREFIX=$(realpath opencv_install) \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_LIST=core,imgcodecs,python3 \
          -DPYTHON3_NUMPY_INCLUDE_DIRS=/home/runner/.local/lib/python3.10/site-packages/numpy/core/include/ \
          -DPYTHON3_INCLUDE_PATH=/usr/include/python3.10 \
          -DPYTHON3_LIBRARIES=/usr/lib/riscv64-linux-gnu/libpython3.10.so \
          -DPYTHON3_EXECUTABLE=/usr/bin/python3.10  \
          -DPYTHON3_CVPY_SUFFIX=".cpython-310-riscv64-linux-gnu.so" \
          -S opencv -B opencv_build

        cmake --build opencv_build -j$(nproc --all)
        cmake --install opencv_build --prefix opencv_install
        tar -cvzf opencv_install.tar.gz opencv_install

    - name: Build OpenVINO
      run: |
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=$(realpath riscv64.toolchain.cmake) \
          -DLIBUSB_LIBRARY=/usr/lib/riscv64-linux-gnu/libusb-1.0.so \
          -DLIBUSB_INCLUDE_DIR=/usr/include/libusb-1.0 \
          -DTHREADING=SEQ \
          -DENABLE_OPENCV=OFF \
          -DENABLE_PYTHON=ON \
          -DENABLE_SAMPLES=OFF \
          -DPYTHON_INCLUDE_DIR=/usr/include/python3.10 \
          -DPYTHON_MODULE_EXTENSION=".so" \
          -DPYTHON_LIBRARY=/usr/lib/riscv64-linux-gnu/libpython3.10.so \
          -S openvino -B openvino_build

        cmake --build openvino_build -j$(nproc --all)
        cmake --install openvino_build --prefix openvino-2022.2-linux-riscv64
        tar -cvzf openvino-2022.2-linux-riscv64.tar.gz openvino-2022.2-linux-riscv64

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "openvino_riscv64"
        path: "openvino*.tar.gz"
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "opencv_riscv64"
        path: "opencv*.tar.gz"
